---
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false

- name: Check if .my.cnf file exists
  stat:
    path: "{{ mysql_root_home }}/.my.cnf"
  register: mysql_root_my_cnf

- name: Initial variable
  set_fact: mysql_root_temp_password=None

- name: Acquire temporary root pass
  shell: >
    awk -F': ' '$0 ~ "temporary password"{print $2}' {{ mysql_log_error }}
  register: mysql_root_temp_password
  when:
    - mysql_install_packages | bool
    - ('5.7.' in mysql_cli_version.stdout) or ('8.0.' in mysql_cli_version.stdout)

- name: Copy .my.cnf file with temporary root password credentials
  template:
    src: "root-temporary-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    mode: 0600
  when:
    - mysql_root_temp_password | bool
    - not mysql_root_my_cnf.stat.exists

- name: Check if temporary root password is expired
  shell: "mysql -NBe 'SELECT NOW();'"
  register: mysql_temp_password_test_result
  when: mysql_root_temp_password | bool
  changed_when: false
  ignore_errors: yes

- name: Check if root password is needed to update
  set_fact: mysql_root_password_update=True
  when:
    - mysql_root_temp_password | bool
    - "'stdout' in mysql_root_temp_password and 'connect-expired-password' in mysql_temp_password_test_result.stdout"

- name: Update MySQL root password for localhost root account (5.7.x or 8.0.x).
  shell: >
    mysql -NBe 'ALTER USER "{{ mysql_root_username }}"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";' --connect-expired-password
  when: mysql_root_password_update

- name: Overwrite .my.cnf file with root password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    mode: 0600
  when: mysql_root_password_update
